spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
  token:
    signing:
      key: b9166333069fd70560aacd61