CREATE TABLE tasks(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    status VARCHAR(50),
    created_at TIMESTAMP,
    is_done BOOLEAN DEFAULT FALSE,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_task_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);